### ISSUE TITLE
希望给出ServerMain.py的文档

### ISSUE THREAD

**Issue by GuHugo95** [Light-Beacon/HomepageBuilder#20]
[FATAL]('D:\\Tools\\server_config.yml not exist!',)
这个server_config.yml到底格式是什么

**Comment by Light-Beacon** [comment]
之后再写文档吧，可以先看下边这个
```
project_path: "Project.yml的绝对路径"
github_secret: "github webhook 的secret（用于获取更新请求并更新工程git）"
```

**Comment by GuHugo95** [comment]
> 之后再写文档吧，可以先看下边这个
> 
> ```
> project_path: "Project.yml的绝对路径"
> github_secret: "github webhook 的secret（用于获取更新请求并更新工程git）"
> ```

懂了，感谢。真心希望可以完善下文档，有很多功能都用不会＞﹏＜

**Comment by Light-Beacon** [comment]
现在准备换新版本了，新的命令见[wiki/开始](https://github.com/Light-Beacon/HomepageBuilder/wiki/开始)
