### ISSUE TITLE
错误的 CanSwap，IsSwapped 属性值

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Light-Beacon/HomepageBuilder#6]
![image](https://github.com/Light-Beacon/HomepageBuilder/assets/109946426/046782e3-d223-4d8c-8cf1-5b3bbdb844ac)
检查发现卡片内有一个 `CanSwap="canswap" IsSwaped="isswaped"`，将两项值改为 `"True"` 即可正常使用

**Comment by JingHai-Lingyun** [comment]
没找到生成函数哪里去了...
~~pr不辽了（悲~~

**Comment by Light-Beacon** [comment]
我本来想用户定义这个东西的，所以没有给默认值
回头改一下吧
